### ISSUE TITLE
Обсуждение модуля корзины

### ISSUE THREAD

**Issue by AnatolyBur** [garpixcms/garpixcms#3]
**Список требований**
- Работа по rest
- Работа на сессиях
- Расширяемость 
- Множественное добавление и удаление товаров
- Хранение товаров в БД

**Comment by crusat** [comment]
Разработка в модуле - https://github.com/garpixcms/garpix_cart

Вопросы или проблемы лучше перетащить туда. Также можно обсудить в чате в телеграм https://t.me/garpixcms
